### ISSUE TITLE
url.path and url.query not used in Kibana

### ISSUE THREAD

**Issue by pihai** [elastic/elastic-otel-dotnet#80] opened 2024-04-04 11:50 UTC
Hi

As it is also visible on [your blog post](https://www.elastic.co/de/blog/elastic-opentelemetry-distribution-dotnet-applications) currently the URL of an HTTP endpoint is not shown correctly. 

![image](https://github.com/elastic/elastic-otel-dotnet/assets/1460563/fc2b3091-44c1-4b7e-a8ee-7cd04537928f)

I think the reason for this is that the `OpenTelemetry.Instrumentation.AspNetCore` library now splits the URL into `url.path` and `url.query`. See also this issue: https://github.com/open-telemetry/opentelemetry-specification/issues/3181

Are we supposed to enrich every activity with `url.full` or how can this be fixed?

**Comment by stevejgordon** [comment] 2024-04-04 13:02
Hi, @pihai.

Congratulations on being the first community issue raiser!

Thanks for submitting this issue. The proper solution is for us to update our intake process to map the updated semantic conventions for incoming (server) HTTP spans to our data model. I'll take action on that on our side.

This is a great example of the benefit this distro can provide. We should be able to include a processor to handle adding any missing attributes the current data mapping depends on so that your code doesn't have to. We'll pick that up and try to include it in a release soon.

**Comment by pihai** [comment] 2024-04-04 18:21
@stevejgordon thank you so much. Now I feel guilty to raise such a minor issue as the first community feedback :D

My team has switched from Elastic APM to Open Telemetry about two years ago. It always felt a bit neglected on the Elastic side. That said, I really appreciate the effort in making the relationship between OTLP and Elastic great. Thank you.

**Comment by stevejgordon** [comment] 2024-04-05 05:37
@pihai No need to feel guilty. This is precisely the feedback we need to help us improve our OTel story, and it is very actionable. We appreciate you taking the time to raise it.

**Comment by stevejgordon** [comment] 2024-04-05 09:56
Raised https://github.com/elastic/apm-data/issues/254 to capture the root cause which will be fixed so that data from any Otel SDK is treated correctly at intake.

**Closed** 2024-04-05 11:14 UTC
Labels: enhancement, community, processor

**Comment by stevejgordon** [comment] 2024-04-05 12:49
@pihai This fix will go out in the next alpha quite soon. As it sounds like you're using the OTel SDK and not our distro, this won't help until the intake fixes are done, which will take a little longer. If you're willing and able, we'd love for you to try out the next alpha and see if the migration is painless (it should be simple) and if this makes the UI more useable for you.

**Comment by pihai** [comment] 2024-04-08 10:46
@stevejgordon wow that was impressively quick :)

You are right, we are not using this distro yet but we strongly consider to in the future. As always things are more complicated than they should: The following issue prevents us from updating `OpenTelemetry.Exporter.OpenTelemetryProtocol` to the version your distro requires: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5083#issuecomment-2036923906

Once this problem is solved I can give your distro a try.
